repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest stable tag
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 24.4.2  # Use the latest stable tag
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0  # Use the latest stable tag
    hooks:
    -   id: flake8
